# DELETE THIS FILE when done

# Setup - Run Only Once-------------------------------------------------------------------
## First create a new postgres database in PGAdmin (local). 
##For this need to have a local postgres server installed on your machine
## This script then creates the table and field setup in the postgres db from a VPro template
library(DBI) 
accessPath <- "./data/VPro64-23Feb2023/VPro64/VPro64.accdb"

source("creds.R") # username, password for pg

accCon <- dbConnect(odbc::odbc(), .connection_string = 
    sprintf("Driver={Microsoft Access Driver (*.mdb, *.accdb)}; DBQ=%s;",
      accessPath))

## connects to postgres db created in PGAdmin
pgCon <- DBI::dbConnect(drv = RPostgres::Postgres(), dbname = 'ava_canada', 
  host = host, port = port, user = username, password = password)
dataTables <- c("Env", "Veg", "Mineral", "Humus", "Admin", "Metadata")
lookupTables <- c("USysAllSpecs", "USysTableOfLists")
convert_types <- function(type) {
  c(VARCHAR = "VARCHAR(255)",
    DATETIME = "TIMESTAMP",
    DOUBLE = "FLOAT",
    REAL = "FLOAT",
    SMALLINT = "SMALLINT",
    LONGCHAR = "VARCHAR(65535)",
    BIT = "BOOLEAN",
    COUNTER = "INTEGER",
    INTEGER = "INTEGER")[type] |> unname()
}
###uses Sample from Vpro as template to create sets of tables for postgrs project
translate_table <- function(accCon, pgCon, name, prefix = '') {
  colTypes <- odbc::odbcListColumns(accCon, sprintf('%s%s', prefix, name))
  pgTypes <- stats::setNames(convert_types(colTypes[['type']]),
    colTypes[['name']])
  if (prefix == 'Sample_') {
    prefix <- 'ava_canada_' ### change name for new project
  }
  name <- tolower(name)
  if (DBI::dbExistsTable(pgCon, name = DBI::SQL(sprintf('%s%s', prefix, name)))) {
    DBI::dbRemoveTable(pgCon, name = DBI::SQL(sprintf('%s%s', prefix, name)))
  }
  sql <- sprintf("CREATE TABLE %s (\n%s\n)", sprintf('%s%s', prefix, name),
    paste(convert_snake_case(names(pgTypes)), pgTypes, collapse = ',\n'))
  # cat(sql)
  DBI::dbExecute(pgCon, sql)
}

convert_snake_case <- function(x) {
  gsub('([a-z]{2,})([A-Z])', '\\1_\\2', x) |> 
    tolower()
}

# Create Tables from sample template to new postgres project (see above)-----------------------------------------------------------

mapply(FUN = translate_table, accCon = list(accCon), pgCon = list(pgCon), 
  name = c(dataTables, lookupTables), 
  prefix = c(rep('Sample_', length(dataTables)), rep('', 
    length(lookupTables)))) 

# Add Pub Table -----------------------------------------------------------
## This is a database of references from BEC may need to change this

accessPath <- "./data/tbl_BEC_References.accdb"

accCon <- dbConnect(odbc::odbc(), .connection_string = 
    sprintf("Driver={Microsoft Access Driver (*.mdb, *.accdb)}; DBQ=%s;",
      accessPath))
colTypes <- odbc::odbcListColumns(accCon, 'tblBEC_References')
pgTypes <- stats::setNames(convert_types(colTypes[['type']]),
  colTypes[['name']])
names(pgTypes)[1] <- 'id'
pgTypes
sql <- sprintf("CREATE TABLE %s (\n%s\n)", sprintf('%s%s', 'ava_canada', 
  '_references'),
  paste(convert_snake_case(names(pgTypes)), pgTypes, collapse = ',\n'))
# cat(sql)
DBI::dbRemoveTable(pgCon, name = DBI::SQL(sprintf('%s%s', 'ava_canada', 
  '_references')))
DBI::dbExecute(pgCon, sql)

# Add Indices -------------------------------------------------------------

# Env
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_env ALTER COLUMN plot_number SET NOT NULL")
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_env ADD PRIMARY KEY (plot_number)")
# Veg
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_veg ALTER COLUMN id SET NOT NULL")
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_veg ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
# Mineral
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_mineral ALTER COLUMN id SET NOT NULL")
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_mineral ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
# Humus
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_humus ALTER COLUMN id SET NOT NULL")
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_humus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
# Admin
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_admin ALTER COLUMN plot SET NOT NULL")
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_admin ADD PRIMARY KEY (plot)")
# Metadata
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_metadata ALTER COLUMN id SET NOT NULL")
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_metadata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
# USysAllSpecs
DBI::dbExecute(pgCon, 
  "ALTER TABLE USysAllSpecs ADD COLUMN row_id SERIAL PRIMARY KEY")
# USysTableOfLists
DBI::dbExecute(pgCon,
  "ALTER TABLE USysTableOfLists ADD COLUMN id SERIAL PRIMARY KEY")
# References
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_references ALTER COLUMN id SET NOT NULL")
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_references ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")

# Fin ---------------------------------------------------------------------

dbDisconnect(accCon)
dbDisconnect(pgCon)

