# Setup -------------------------------------------------------------------

library(DBI) 
accessPath <- "./data/AVA_Canada_Master.accdb"
postgresPath <- 
source("creds.R") # username, password for pg

accCon <- dbConnect(odbc::odbc(), .connection_string = 
    sprintf("Driver={Microsoft Access Driver (*.mdb, *.accdb)}; DBQ=%s;",
      accessPath))
###must have created pg database in PGAdmin
pgCon <- DBI::dbConnect(drv = RPostgres::Postgres(), dbname = 'ava_canada', 
  host = Sys.getenv('PG_SM_HOST'), user = username, password = password)
dataTables <- c("env", "veg", "mineral", "humus", "admin", "metadata")
lookupTables <- c("USysAllSpecs", "USysTableOfLists")
convert_types <- function(type) {
  c(VARCHAR = "VARCHAR(255)",
    DATETIME = "TIMESTAMP",
    DOUBLE = "FLOAT",
    REAL = "FLOAT",
    SMALLINT = "SMALLINT",
    LONGCHAR = "VARCHAR(65535)",
    BIT = "BOOLEAN",
    COUNTER = "INTEGER",
    INTEGER = "INTEGER")[type] |> unname()
}
translate_table <- function(accCon, pgCon, name, prefix = '') {
  colTypes <- odbc::odbcListColumns(accCon, sprintf('%s%s', prefix, name))
  pgTypes <- stats::setNames(convert_types(colTypes[['type']]),
    colTypes[['name']])
  if (prefix == 'Sample_') {
    prefix <- 'ava_canada_'
  }
  DBI::dbRemoveTable(pgCon, name = DBI::SQL(sprintf('%s%s', prefix, name)))
  sql <- sprintf("CREATE TABLE %s (\n%s\n)", sprintf('%s%s', prefix, name),
    paste(convert_snake_case(names(pgTypes)), pgTypes, collapse = ',\n'))
  # cat(sql)
  DBI::dbExecute(pgCon, sql)
}

convert_snake_case <- function(x) {
  gsub('([a-z]{2,})([A-Z])', '\\1_\\2', x) |> 
    tolower()
}

# Create Tables -----------------------------------------------------------

mapply(FUN = translate_table, accCon = list(accCon), pgCon = list(pgCon), 
  name = c(dataTables, lookupTables), 
  prefix = c(rep('ava_canada_', length(dataTables)), rep('', 
    length(lookupTables)))) 

# Add Pub Table -----------------------------------------------------------

accessPath <- "./data/tbl_BEC_References.accdb"
accCon <- dbConnect(odbc::odbc(), .connection_string = 
    sprintf("Driver={Microsoft Access Driver (*.mdb, *.accdb)}; DBQ=%s;",
      accessPath))
colTypes <- odbc::odbcListColumns(accCon, 'tblBEC_References')
pgTypes <- stats::setNames(convert_types(colTypes[['type']]),
  colTypes[['name']])
names(pgTypes)[1] <- 'id'
pgTypes
sql <- sprintf("CREATE TABLE %s (\n%s\n)", sprintf('%s%s', 'ava_canada', 
  '_references'),
  paste(convert_snake_case(names(pgTypes)), pgTypes, collapse = ',\n'))
# cat(sql)
DBI::dbRemoveTable(pgCon, name = DBI::SQL(sprintf('%s%s', 'ava_canada', 
  '_references')))
DBI::dbExecute(pgCon, sql)

# Add Indices -------------------------------------------------------------

# Env
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_env ALTER COLUMN plot_number SET NOT NULL")
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_Env ADD PRIMARY KEY (plot_number)")
# Veg
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_Veg ALTER COLUMN id SET NOT NULL")
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_Veg ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
# Mineral
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_Mineral ALTER COLUMN id SET NOT NULL")
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_Mineral ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
# Humus
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_Humus ALTER COLUMN id SET NOT NULL")
DBI::dbExecute(pgCon, 
  "ALTER TABLE AVA_Canada_MasterBECMaster_Humus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
# Admin
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_Admin ALTER COLUMN plot SET NOT NULL")
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_Admin ADD PRIMARY KEY (plot)")
# Metadata
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_Metadata ALTER COLUMN id SET NOT NULL")
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_Metadata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
# USysAllSpecs
DBI::dbExecute(pgCon, 
  "ALTER TABLE USysAllSpecs ADD COLUMN row_id SERIAL PRIMARY KEY")
# USysTableOfLists
DBI::dbExecute(pgCon,
  "ALTER TABLE USysTableOfLists ADD COLUMN id SERIAL PRIMARY KEY")
# References
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_references ALTER COLUMN id SET NOT NULL")
DBI::dbExecute(pgCon, 
  "ALTER TABLE ava_canada_references ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")

# Fin ---------------------------------------------------------------------

dbDisconnect(accCon)
dbDisconnect(pgCon)
